### ISSUE TITLE
PHP 7 causes exception on usage of Int as classname because Int is reserved on PHP7

### ISSUE THREAD

**Issue by pboethig** [UltimateModuleCreator/Umc_Base#13] opened 2015-12-20 11:38 UTC
on php magento setup:di:compile an exception is rison "Cannot Use Int because its reserved".

How can i push a branch with a patch to solve the problem?

kind regards

Peter

**Comment by UltimateModuleCreator** [comment] 2015-12-21 12:22
@pboethig You can see here how pull requests work: https://help.github.com/articles/using-pull-requests/ , but if there is not much code, you can send me the fix.  
I have a hunch you are talking about this class https://github.com/UltimateModuleCreator/Umc_Base/blob/master/Model/Core/Attribute/Type/Int.php. Am I right? It should have a different name.

**Comment by pboethig** [comment] 2015-12-21 12:51
Hi Marius,

Yes, you are right.

Please make a grep for "Int" to find all usages of the Type class and all
inheritances.I see, that the generated di.xml in generated modules
containing the classname "Int" too,

I found 4 Files to change.

Is it possible that you are using classnames like "String" etc too?

Seems, that the zend programmer are now reservating all of the typenames.
Thats realy annoying because it breaks bc.

I will send you the fix today in the evening.


Kind regards

Peter



2015-12-21 13:22 GMT+01:00 Marius Strajeru <notifications@github.com>:

**Comment by pboethig** [comment] 2015-12-22 05:01
Hi Marius,

Attached you find the fixed version.

Please make a diff to find the changes.

kind regards


Peter

2015-12-21 13:51 GMT+01:00 Peter Böthig <pboethig@gmail.com>:

**Comment by UltimateModuleCreator** [comment] 2016-12-05 15:20
Duplicate of #26

**Comment by UltimateModuleCreator** [comment] 2017-05-22 06:42
This should be fixed in 2.0.0-beta1

**Closed by UltimateModuleCreator** 2017-05-22 06:42 UTC
Labels: bug
