### ISSUE TITLE
Note: Tree

### ISSUE THREAD

**Issue by rdeelstra** [UltimateModuleCreator/Umc_Base#11] opened 2015-12-16 15:07 UTC
Fatal error:  Call to a member function getId() on a non-object in /magento2/lib/internal/Magento/Framework/Data/Tree/Dbp.php on line 380

That is within public function loadEnsuredNodes($category, $rootNode)

When I add one record in the database with position 0 everything seems to be working fine again.

**Comment by UltimateModuleCreator** [comment] 2015-12-16 15:26
@rdeelstra One record should be inserted by the [`installData.php`](https://github.com/UltimateModuleCreator/Umc_Base/blob/master/etc/source/Setup/InstallData.php/0200_entity_setup) script for tree entities.  
But I will check again.  
Can you send me the file `var/umc/[Namespace]_[Module].xml` at ultimate.module.creator@gmail.com so I can reproduce your exact extension and see the problem?

**Comment by rdeelstra** [comment] 2015-12-16 15:45
I have send it. The strange thing is when I recreated the module with one entity instead of two it did insert a ROOT row in the database. Maybe something was wrong in my environment, I was debugging some things maybe something was being blocked when installing or something like that.

Btw you guys are awesome for creating such a module, great idea :-)

**Comment by UltimateModuleCreator** [comment] 2016-04-21 06:04
I will close this for now as I cannot reproduce it. Anyway, the UMC will go through a lot of changes in the next period.

**Closed by UltimateModuleCreator** 2016-04-21 06:04 UTC
